name: flutter_barcode_listener
description: Listen for any hardware barcode scanner without any manufacturer SDK
version: 1.0.0
publish_to: http://nexus.gojitsu.com:7777
axlehire_project_type: package

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  axlehire_lints:
    version: ^5.0.1
    hosted:
      name: axlehire_lints
      url: http://nexus.axlehire.com:7777
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
